<h1>Usuários</h1>
<button onclick="location.href='/admin/users/save'">Novo usuário</button>

<table class="table">
    <thead>
        <th>Login</th><th>Role</th>
    </thead>
    <tbody>
        <?php foreach($users as $user){ ?>
        <tr>
            <td>
                <?php echo $user['login']; ?>
            </td>
            <td>
                <?php echo $user['role']; ?>
            </td>
        </tr>
        <?php } ?>
    </tbody>  
</table>