<?php if ($this->pageCount): ?>
    <div class="pagination pagination-centered">
        <ul>
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>

                <a href="<?php echo $this->url($this->route); ?>/index/index/page/<?php echo $this->previous; ?>">
                    <<
                </a>

            <?php else: ?>

                <a href="#">
                    <<
                </a>

            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>

                    <a href="<?php echo $this->url($this->route); ?>/index/index/page/<?php echo $page; ?>">
                        <?php echo $page; ?>
                    </a>

                <?php else: ?>

                    <a href="#"><?php echo $page; ?></a>

                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>

                <a href="<?php echo $this->url($this->route); ?>/index/index/page/<?php echo $this->next; ?>">
                    >>
                </a>

            <?php else: ?>

                <a href="#">
                    >>
                </a>

            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>